export const constants = {
    
    GET_PIZZAS_REQUEST: 'GET_PIZZAS_REQUEST',
    GET_PIZZAS_SUCCESS: 'GET_PIZZAS_SUCCESS',
    GET_PIZZAS_FAILED: 'GET_PIZZAS_FAILED',

    ADD_TO_CART: 'ADD_TO_CART',
    DELETE_FROM_CART: 'DELETE_FROM_CART',

    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILED: 'USER_REGISTER_FAILED',

    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',

    PLACE_ORDER_REQUEST: 'PLACE_ORDER_REQUEST',
    PLACE_ORDER_SUCCESS: 'PLACE_ORDER_SUCCESS',
    PLACE_ORDER_FAILED: 'PLACE_ORDER_FAILED',

}