export const constants = {
    GET_PIZZAS_REQUEST: 'GET_PIZZAS_REQUEST',
    GET_PIZZAS_SUCCESS: 'GET_PIZZAS_SUCCESS',
    GET_PIZZAS_FAILED: 'GET_PIZZAS_FAILED',

    ADD_TO_CART: 'ADD_TO_CART',
    DELETE_FROM_CART: 'DELETE_FROM_CART',

}